# General Sequence Data Methods

In [4]:
import numpy as np

In [5]:
arr = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])

In [6]:
print(arr[0][1])

[4 5 6]


In [7]:
s={1,2,4,5}
l=[]
for i in range(len(s)):
    l +=[1+i]

In [8]:
print(l)

[1, 2, 3, 4]


In [10]:
arr = np.array(np.arange(0,15))

In [12]:
print(arr.reshape(3,5))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [16]:
place ="Chennai"
print("My friends house is in {}".format("Chennai"))

My friends house is in Chennai


In [19]:
t1=(1,2,"tuple",4)
t2=(5,6,7)
x=t2[t1[1]]
print (x)

7


In [22]:
t3=(list(t1), list(t2))
print (t3)

([1, 2, 'tuple', 4], [5, 6, 7])


In [23]:
t1.append(5)
print (t1)

AttributeError: 'tuple' object has no attribute 'append'

In [24]:
d={1:"Pyhton",2:[1,2,3]}
d["one"]=1
print (d)

{1: 'Pyhton', 2: [1, 2, 3], 'one': 1}


In [26]:
d={1:"Pyhton",2:[1,2,3]}
d. update({'one' : 2})
print (d)

{1: 'Pyhton', 2: [1, 2, 3], 'one': 2}


In [27]:
student = {'name': 'Jane', 'age': 25, 'courses': ['Math', 'Statistics']}

In [31]:
student['phone'] = '123-456'
student.update({'age' : 26})
print (student)

{'name': 'Jane', 'age': 26, 'courses': ['Math', 'Statistics'], 'phone': '123-456'}


In [32]:
s="Mahesh"
l=[]
for i in s:
    l.append(i.capitalize())
print (l)    

['M', 'A', 'H', 'E', 'S', 'H']
